"""migration

Revision ID: d6adcbaa71aa
Revises: fb7170deab93
Create Date: 2025-08-28 08:36:06.718137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6adcbaa71aa'
down_revision = 'fb7170deab93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_views', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('login_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_streak')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'profile_views')
    # ### end Alembic commands ###
