"""your message

Revision ID: d955aac3462d
Revises: fb7170deab93
Create Date: 2025-08-28 18:56:44.785027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd955aac3462d'
down_revision = 'fb7170deab93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('plan_paystack_plan_code_key'), type_='unique')
        batch_op.drop_column('paystack_plan_code')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('paystack_subscription_code')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_streak')
        batch_op.drop_column('last_login')
        batch_op.drop_column('profile_views')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_subscription_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_plan_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('plan_paystack_plan_code_key'), ['paystack_plan_code'])

    op.drop_table('payment')
    # ### end Alembic commands ###
